[general]
import = ["~/.config/alacritty/themes/themes/github_light.toml"]

[env]
TERM = "xterm-256color"
EDITOR = "emacs"

[window]
dimensions = { columns = 100, lines = 50 }
padding = { x = 13, y = 13 }
startup_mode = "Maximized"
decorations_theme_variant = "Dark"
decorations = "Transparent"
option_as_alt = "Both"

[scrolling]
history = 10000
multiplier = 3

[font]
normal = { family = "Monolisa Variable", style = "Regular" }
bold = { style = "SemiBold" }
size = 15

[selection]
save_to_clipboard = true
